name: delivery
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  shared_preferences: ^2.0.11
  overlay_support: ^1.2.1
  cupertino_icons: ^1.0.2
  google_fonts: ^2.2.0
  line_icons: ^2.0.1
  # yandex_mapkit: ^2.0.1
  provider: ^6.0.2
  intl: ^0.17.0
  scale_button: ^2.1.2
  image: ^3.1.3
  collection: any
  another_flushbar: ^1.10.28
  flutter_slidable: ^1.2.0
  url_launcher: ^6.0.20
  google_maps_flutter: ^2.1.3
  firebase_core: ^1.11.0
  firebase_messaging: ^11.2.13
  geolocator: ^8.2.0
  webviewx: ^0.2.1
  loading_animation_widget: ^1.2.0+3
  scroll_to_index: ^3.0.1
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  assets:
    - lib/assets/logo.png

  uses-material-design: true
